CREATE DATABASE HOTEL

USE HOTEL

CREATE TABLE ROOMTYPES(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL
)



CREATE TABLE CUSTOMERS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL
)



CREATE TABLE PAYMENTS(
ID INT PRIMARY KEY IDENTITY,
SUMMA MONEY
)


CREATE TABLE SPENDINGS(
ID INT PRIMARY KEY IDENTITY,
SUMMA MONEY
)

CREATE TABLE ROOMS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
TYPE INT REFERENCES ROOMTYPES(ID),
PRICEID INT REFERENCES PAYMENTS(ID)
)

CREATE TABLE RESERVATIONS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
CUSTOMERID INT REFERENCES CUSTOMERS(ID),
ROOMID INT REFERENCES ROOMS(ID),
SPENDINGSID INT REFERENCES SPENDINGS(ID)
)

CREATE VIEW SAVERESERVS
AS
SELECT CUSTOMERS.NAME 'Customer', ROOMS.NAME 'Room', ROOMTYPES.NAME 'Type', PAYMENTS.SUMMA 'Payment', SPENDINGS.SUMMA 'Spending', RESERVATIONS.NAME 'Reservation' FROM CUSTOMERS
JOIN RESERVATIONS 
ON CUSTOMERS.ID = RESERVATIONS.CUSTOMERID
JOIN ROOMS
ON ROOMS.ID = RESERVATIONS.ROOMID
JOIN ROOMTYPES
ON ROOMS.TYPE = ROOMTYPES.ID
JOIN PAYMENTS
ON PAYMENTS.ID = ROOMS.PRICEID
JOIN SPENDINGS
ON SPENDINGS.ID = RESERVATIONS.SPENDINGSID

CREATE PROCEDURE MAKEENDIRIM @ENDIR MONEY
AS
SELECT PAYMENTS.SUMMA - @ENDIR FROM PAYMENTS

EXEC MAKEENDIRIM 5

CREATE FUNCTION ENDIRIMELE(@endir MONEY)
RETURNS MONEY
BEGIN
DECLARE @CEMI MONEY
SELECT @CEMI = PAYMENTS.SUMMA - @endir FROM PAYMENTS
RETURN @CEMI
END

SELECT dbo.ENDIRIMELE(5)

CREATE TRIGGER SILINENDESELECT
ON RESERVATIONS
AFTER DELETE
AS
BEGIN
SELECT * FROM RESERVATIONS
END

DELETE  FROM RESERVATIONS
WHERE NAME = '2ND'
